# docker-compose configuration for running unit + integration tests
version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  mongo:
    image: mongo
    ports:
      - "27017:27017"
